services:
  voicemail-transcriber:
    build: .
    image: voicemail-transcriber:latest
    container_name: voicemail-transcriber
    gpus: all            # <-- actually gives the container the GPU
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - voicemail-net

networks:
  voicemail-net:
    driver: bridge       # <-- fix typo
